version: 2

jobs:
  build:
    working_directory: ~/stack-attack
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v2-node-{{ arch }}-{{ .Branch }}-
            - v2-node-{{ arch }}-
      - run:
          name: Install dependencies and build
          command:
            yarn --frozen-lockfile --cache-folder ~/.cache/yarn
            --non-interactive
      - save_cache:
          key: v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - store_artifacts:
          path: dist
      - run:
          name: Run Linters
          command: yarn lint
      - run:
          name: Test code
          environment:
            NODE_ENV: test
          command: |
            set -e
            yarn test
            yarn codecov --disable=gcov -f ./coverage/coverage-final.json
      - store_test_results:
          path: test-reports
      - run:
          name: Create zipped build
          command: zip stack-attack.zip dist
      - store_artifacts:
          path: stack-attack.zip
